# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pseudo',
            field=models.CharField(max_length=50, verbose_name='Pseudo'),
        ),
    ]
