# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_blog', '0002_auto_20161226_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Article publi\xe9 ?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Commentaire publie ?'),
        ),
    ]
