# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_blog', '0003_auto_20161226_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=30),
        ),
    ]
